---
- name: KubeSphere | Check core components (1)
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-system ks-account
  register: check_account
  failed_when: "check_account.stderr and 'NotFound' not in check_account.stderr"

- name: KubeSphere | Check core components (2)
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-system ks-apigateway
  register: check_apigateway
  failed_when: "check_apigateway.stderr and 'NotFound' not in check_apigateway.stderr"

- name: KubeSphere | Check core components (3)
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-system ks-account -o jsonpath='{.spec.replicas}'
  register: check_account_replicas
  failed_when: "check_account_replicas.stderr and 'NotFound' not in check_account_replicas.stderr"
  when:
    - check_account.rc == 0

- name: KubeSphere | Check core components (4)
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-system ks-apigateway -o jsonpath='{.spec.replicas}'
  register: check_apigateway_replicas
  failed_when: "check_apigateway_replicas.stderr and 'NotFound' not in check_apigateway_replicas.stderr"
  when:
    - check_apigateway.rc == 0

- block:
  - name: KubeSphere | Update ks-core status
    shell: >
      {{ bin_dir }}/kubectl patch cc ks-installer
      --type merge
      -p '{"status": {"core": {"migration": true}}}'
      -n kubesphere-system
    register: import
    failed_when: "import.stderr and 'Warning' not in import.stderr"
    until: import is succeeded
    retries: 5
    delay: 3
  - set_fact:
      ks_upgrade: True
  when:
    - check_account.rc == 0
    - check_apigateway.rc == 0
    - check_account_replicas.stdout != "0"
    - check_apigateway_replicas.stdout != "0"
    - "'NotFound' not in check_account.stderr"
    - "'NotFound' not in check_apigateway.stderr"
    - "'NotFound' not in check_account_replicas.stderr"
    - "'NotFound' not in check_apigateway_replicas.stderr"


- name: KubeSphere | Create KubeSphere dir
  file:
    path: "{{ kubesphere_dir }}"
    state: directory
    mode: 0755


- name: KubeSphere | Getting installation init files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "ks-init"

- import_tasks: ks-init.yaml
  when: ks_upgrade is not defined or (ks_upgrade != True)


- name: KubeSphere | Init KubeSphere
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-init/{{ item }}"
  loop:
    - "iam-accounts.yaml"
    - "webhook-secret.yaml"
    - "users.iam.kubesphere.io.yaml"
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr and 'Warning' not in import.stderr"


- name: KubeSphere | Getting controls-system file
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.file }}"
  with_items:
    - { name: kubesphere-controls-system, file: kubesphere-controls-system.yaml }


- name: KubeSphere | Installing controls-system
  command: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/kubesphere-controls-system.yaml  -n kubesphere-controls-system"
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr"


- name: KubeSphere | Generate kubeconfig-admin
  shell: >
    /bin/bash {{ kubesphere_dir }}/ks-init/generate-kubeconfig.sh
  when:
    - openpitrix.enabled is defined and openpitrix.enabled